title: Michael McCarthy # your name (or website title) here
logo: "/images/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello and welcome to my portfolio website! I am a math teacher with a degree in Mathematics and a Master Degree in Teaching. Throughout my career, I have always been passionate about mathematics and have enjoyed sharing my knowedge and love of the subject with my students. In recent years, I have become increasingly interested in the field of data analytics and have decided to make a transition into this exciting field.
  <br><br>
  As a math educator and student, I have a strong foundation in mathematics and problem solving skills combined with the communication skills to translate complex ideas and results into easy to understand language. I am currently working on building my skills in data analysis and visualization and am excited to see where this journey takes me. On this website you will find my professional information and a selection of my projects in data analytics.
  
  <br><br>
  <a href="https://www.linkedin.com/in/michael-mccarthy-698000a5">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-F2LNSZNQXH # your Google Analytics tracking ID here




