title: Michael McCarthy 
logo: "/images/Profile.jpg?raw=true"
description: > 
  Hello and welcome to my portfolio. I'm a math teacher with a degree in Mathematics and a Master's in Teaching. I've always been passionate about mathematics and have enjoyed sharing my knowledge and love of the subject with my students. Recently, I have become increasingly interested in data analytics and decided to transition into this exciting field.
  <br><br>
  I have a strong foundation in mathematics in addition to the problem solving and communication skills to simplify complex ideas and results for stakeholders. I'm currently building my skills in data analysis and visualization. On this website, you will find my professional information and a selection of my projects.
  <br>
  <a href="https://www.linkedin.com/in/michael-mccarthy-698000a5">View My LinkedIn Profile</a>
  <br>
  <a href="https://public.tableau.com/app/profile/michael.mccarthy7631"> View My Tableau Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-252457404-1
