title: Michael McCarthy 
logo: "/images/Profile.jpg?raw=true"
description: > 
  I'm a dynamic Research Consultant driven by results, armed with a BS in Mathematics, an MA in Teaching, and an ongoing pursuit of an MS in Analytics at Georgia Tech. My teaching background exemplifies my fervor for mathematics, showcasing my adaptability in any environment. Now, I'm poised to channel these talents into the realm of data analytics, continuously augmenting my technical expertise.
  <br><br>
  My solid grounding in mathematics is complemented by adept problem-solving and communication abilities, enabling me to distill intricate concepts for stakeholders. Explore this platform for a glimpse into my professional journey and a curated collection of my projects outside of my work responsibilities.
  
theme: jekyll-theme-minimal
google_analytics: UA-252457404-1
