title: Michael McCarthy 
logo: "/images/Profile.jpg?raw=true"
description: > 
  I am a results-oriented Budget Data Analyst with a strong foundation in data analysis, financial modeling, and strategic planning. Currently pursuing an MS in Analytics at Georgia Tech, I am enhancing my data science expertise to drive more effective decision-making in complex financial environments.
  <br><br>
  In my current role in state government, I specialize in building advanced Excel tools for budgeting, leveraging SQL for data querying, and administering online budget management and reporting systems. I am passionate about turning complex datasets into actionable insights and developing tools that streamline processes and enhance transparency.
  
theme: jekyll-theme-minimal
google_analytics: UA-252457404-1
